name: secret_gallery
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Galería y permisos
  photo_manager: ^3.3.0
  permission_handler: ^11.3.1

  # Almacenamiento seguro
  flutter_secure_storage: ^9.2.2
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  path: ^1.9.0

  # Encriptación
  encrypt: ^5.0.3
  pointycastle: ^3.9.1

  # UI
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.4.1
  fluttertoast: ^8.2.8
  google_fonts: ^6.2.1

  # PIN
  pinput: ^5.0.0

  # Video
  video_player: ^2.8.6
  video_thumbnail: ^0.5.3
  chewie: ^1.8.5

  # Sensores y utilidades
  sensors_plus: ^7.1.0
  wakelock_plus: ^1.2.8
  screen_brightness: ^2.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true